### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Currerius** [ericnorris/node-cdb#2]
This is probably a bit misplaced and you are _not_ a newbee JS tutor. So sorry.
But:
Is it troublesome to extend your excellent examples to the typical user case where you call it from inside a function and the data part is not simply printed to the console.log, but passed back through the callback chain to the calling function? I guess it is easy if you know how to do it, but I am pulling my hairs on these freaky callback chains :package: 
    var readable = require('constant-db').readable;

```
var getTheRecord = function(key){

    var reader = new readable('./cdbfile');

    reader.open(function cdbOpened(err) {

        reader.get( key , function gotRecord(err, data) {

            return data;  // instead of console.log(data); 

            reader.close(function cdbClosed(err) {
                console.log('awesome!');
            });
        });
    });
});
```

Which gives you "hello world!" when calling
console.log( getTheRecord('meow'));

I am banging my head against the wall :) This exercise is very informative about the intention of nonblocking code - that it does not block and not wait... whatever I do I get returned "undefined" since the engine simply does not wait for the variable to return.... I looked at promises, but I think one would rather use callbacks.

Sorry for bugging you, but I suspect it is an easy issue for a node pro?

Thanks anyway for your brilliant tool and I will figure it out anyway anyway :)

R

**Comment by ericnorris** [comment]
You are exactly correct, that code will return `undefined` when executed. The issue is that it appears you are still thinking synchronously - you want getTheRecord to synchronously return the record you asked for.

Modifying the code to take a callback gives you this example:

```
var getTheRecord = function(key, callback){

    var reader = new readable('./cdbfile');

    reader.open(function cdbOpened(err) {

        reader.get( key , function gotRecord(err, data) {

            reader.close(function cdbClosed(err) {
                callback(data);
            });
        });
    });
});
```

Now this function will open the CDB, get the record, and close the CDB, then call the callback. I wouldn't recommend using this in an actual application as it would have terrible performance.

Take a look at a couple tutorials (like [this one](https://github.com/maxogden/art-of-node#callbacks)) and hopefully you'll figure it out!

**Comment by Currerius** [comment]
Thank you! That was very kind _and_ educating. I am banging my head against the wall with the asynchronous paradigm - it must be a real revelation when one finally gets it.
